export const AUTH_ACTION = {
  LOGIN: 'AUTH_ACTION/LOGIN',
  REGISTER: 'AUTH_ACTION/REGISTER',
  LOGOUT: 'AUTH_ACTION/LOGOUT',
  GET_USER: 'AUTH_ACTION/GET_USER',
  CLEAR_AUTH: 'AUTH_ACTION/CLEAR_AUTH',
  ERROR_MESSAGE: 'AUTH_ACTION/ERROR_MESSAGE',
  CLEAR_ERRORS: 'AUTH_ACTION/CLEAR_ERRORS',
};
